disabled_rules: # Default Rules에서 비활성화할 규칙
    
    # 라인 뒤에 공백이 없어야 합니다. https://realm.github.io/SwiftLint/trailing_whitespace.html
    - trailing_whitespace
    
    # 강제 캐스팅은 피해야합니다. https://realm.github.io/SwiftLint/force_cast.html
    - force_cast
    
    # 강제 언래핑은 피해야합니다. https://realm.github.io/SwiftLint/force_unwrapping.html
    - force_unwrapping
    
    - line_length
    - function_body_length
    - function_parameter_count
    - type_body_length
    - void_return
    - cyclomatic_complexity
    - file_length
    - identifier_name
    
opt_in_rules:  # 기본(default) 룰이 아닌 룰들을 활성화
    # .count==0 보다는 .isEmpty를 사용하는 것이 좋습니다. https://realm.github.io/SwiftLint/empty_count.html
    - empty_count
    
    # 빈 String 문자열과 비교하는 것 보다는 .isEmpty를 사용하는 것이 좋습니다. https://realm.github.io/SwiftLint/empty_string.html
    - empty_string
    
    # operation 사용시 양옆에 공백이 있어야 합니다. https://realm.github.io/SwiftLint/operator_whitespace.html
    - operator_usage_whitespace
    
    # {}사용시 앞에 공백이 있어야 합니다. https://realm.github.io/SwiftLint/opening_brace.html
    - opening_brace

    # comma 앞에는 여백이 없고 뒤에는 공백이 있어야합니다. https://realm.github.io/SwiftLint/comma.html
    - comma

    # 주석 // 다음에 공백이 있어야 합니다.
    - comment_spacing

